language: node_js
node_js:
- node
env:
  global:
    secure: ad3VgQVizL5yANhxhljzRCOsSQ4WA5Kw+hR33cAfoRV+gjhixa/Xq8hA5BV366DRak8GcpjBTkPbj0J6ibYePaZMfGUIhSVYFb9VGjnFP+IxLobgVAn6TTfVYNG0nsySBEfiHMj4flLPUwJQxVdpTtJWmqlFqZA/BieGXcUvT7B+kIDs6udT0shFNK2iNE2QPtkJBGiyUS7Jrlsi8Y0HUmGWidHX2gnReBJS076zXTApkNj3n3mTWb0ASo0b65qrwe+s59a2EQJC8+0Hbvkw48YJ/rAh1O000c6bpLtPfHrfdGALdlE0B9WwMx2TtwB8pjldbwoiEL0Wg8gMJaetVtGKNZbrM9Mw/2Ptei0cHY66P57dW5h/N+/hrxMK6pCvNHJygaKFwRugA3VPQQUUsdEZ3X/L4HymcTgRM1LXk/wnM6ggzhatmtgVcW2Bz3teyV/Ov5UeWQiuuWkJkmLFjZkuGHUtZr4Qq8Imylep3d8cUeE7afpLxvgJMZ78IARxj/yCP+Wk2LeQP2dY7NCuzx1zkPjpOile73t7x+q4Uz/TuvdffvMD+aJIJKQCRcnpXR3U1oZaxjma2raeLsXPEynpVFlfURUHozphD8Ur9qCRjiFff3Y8rzdlTwEwJLsuUrceL77ygM+W8FioGr5n2sW5yCaXvbrFOnPcgXyRx2s=
